#!/usr/bin/env bash
# Commands faciliating the following requierments:
#	Install nginx on server 'web-01'
#	Nginx should be listening on port 80
#	When querying Nginx at its root / with a GET request (requesting a page) using curl, it must return a page that contains the string Hello World!

sudo apt-get -y upgrade
sudo apt-get -y update
sudo apt-get -y install nginx
sudo echo "Hello Dem, My World!" > /var/www/html/index.html
sudo nginx -s reload
