#!/usr/bin/env bash
#Redirection 301 moved permanently

#Update packages
sudo apt-get update
sudo apt-get install -y nginx

#Create an index.html page
echo "What's up World!" | sudo tee /var/www/html/index.html
echo "What's up Dem!" | sudo tee /usr/share/nginx/html/index.html

#Handle redirects
string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/kal-kyokya permanent;"
sudo sed -i "s/server_name _;/$string/" /etc/nginx/sites-enabled/default

#Restart Nginx service
sudo service nginx restart
