#!/usr/bin/env bash
# Installs a Port 80 listening Nginx with the following configurations:

sudo apt-get update -y; sudo apt-get upgrade -y
sudo apt-get install -y nginx

sudo mkdir -p /data/web_static/releases/test
sudo mkdir -p /data/web_static/shared

sudo echo '
<!DOCTYPE html>
<html>
  <head> Releases Test File </head>

  <body background-color="grey">
    <p> Test-Test, One-Two, One-Two </p>
  </body>

  </html> ' > /data/web_static/releases/test/index.html

sudo ln -sf /data/web_static/releases/test /data/web_static/current

chown -R ubuntu /data
chgrp -R ubuntu /data

sudo mkdir -p /var/www/html

printf %s "
<!DOCTYPE html>
<html>
<head>
<title>kalkyokya.tech</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
    a {
        align: center;
    }
</style>
</head>
<body>
<h1 align="center">Welcome to Jean-Paul KYOKYA's Website !</h1>
<p>If you see this page, it means I have shared the link ith you.
Be proud, you are among the first, if not the very first.</p>

<p>For online documentation and support contact me through:<br/>
GitHub:<br/>
<a href="https://www.github.com/kal-kyokya/" target="_blank"><img alt="GitHub" src="https://img.shields.io/badge/github-%2312100E.svg?&style=for-the-badge&logo=github&logoColor=pink" /></a><br/>
Instagram:<br/>
<a href="https://www.instagram.com/kal_kyokya/" target="_blank"><img alt="Instagram" src="https://img.shields.io/badge/instagram-%23E72B96.svg?&style=for-the-badge&logo=instagram&logoColor=white" /></a><br/>
LinkedIn:<br/>
<a href="https://www.linkedin.com/in/jean-paul-kyokya-b21892223/" target="_blank"><img alt="LinkedIn" src="https://img.shields.io/badge/linkedin-%230077B5.svg?&style=for-the-badge&logo=linkedin&logoColor=white" /></a>.</p>

<p><em>Thank you for using kalkyokya.tech.</em></p>
</body>
</html> " > /var/www/html/index.html

printf %s "
<!DOCTYPE html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title> 404 Error </title>
  <style>
    body {
        background-color: black;
        color: grey;
        margin: 0;
        padding: 0;
        height: 100vh;
        display: flex;
        flex-direction: column;
        justify-content: space-between;
    }

    .footer {
      padding: 10px;
      text-align: center;
      position: sticky;
      bottom: 0;
      width: 100%;
      border-top: 1px solid #CCCCCC;
    }
  </style>
</head>

<body>
  <h1 align="center" flex-grow="1">
    <em>
      Page not found
    </em>
  </h1>

  <div class="footer">
    <p>
      <em>
        Thank you for using kalkyokya.tech
      </em>
    </p>
  </div>
</body> " > /etc/nginx/html/404.html

printf %s "
server {
    listen 80;
    listen [::]:80 default_server;

    add_header X-Served-By '$HOSTNAME';

    root   /var/www/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 https://www.github.com/kal-kyokya;
    }

    location /entertain_me {
        return 301 http://www.cuberule.com/;
    }

    location /hbnb_static {
        alias /data/web_static/current/;
        index index.html;
    }

    error_page 404 /404.html;

    location /404 {
      root /var/www/html;
      internal;
    }
}" > /etc/nginx/sites-available/default

sudo nginx -t

sudo service nginx restart
