#!/usr/bin/env bash
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

touch /var/run/myscript.pid
if [ -e /var/run/myscript.pid ]; then
	pid=$(pgrep 100-process_and_pid_file)
	echo $pid > /var/run/myscript.pid

fi

while [ 1 ]
do
	echo "To infinity and beyond"
	sleep 2
	trap "echo 'I hate the kill command'; rm /var/run/myscript.pid; exit" SIGTERM SIGQUIT
	trap "echo 'Y U no love me?!'" SIGINT

done
