#!/usr/bin/env bash
# Manages another process remotely

if [ "$1" = "start" ]
then
	./manage_my_process &
	touch /var/run/my_process.pid
	echo "$!" > /var/run/my_process.pid
	echo "manage_my_process started"

elif [ "$1" = "stop" ]
then
	kill "$(cat /var/run/my_process.pid)"
	rm /var/run/my_process.pid
	echo "manage_my_process stopped"


elif [ "$1" = "restart" ]
then
	pkill -SIGSTOP "$(pgrep -f manage_my_process)"
	rm /var/run/my_process.pid
	pkill -SIGCONT "$(pgrep -f manage_my_process)"
	pgrep -f manage_my_process > /var/run/my_process.pid
	echo "manage_my_process restarted"
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
