#!/usr/bin/env bash
#Implement fizzbuzz as a bash script.

i=1

while [ $i -lt 101 ]
do
	if (( i % 5 == 0 && i % 3 == 0 )); then
	   	   echo "FizzBuzz"
	elif [ $((i % 3)) -eq 0 ]; then
	   echo "Fizz"
	elif [ $((i % 5)) -eq 0 ]; then
	     echo "Buzz"
	else
		echo "$i"
	fi
	((i++))

done
