#!/usr/bin/env bash
#Prints a string n times and make a change for the (n-x)th print.

i=0

while [ $i -lt 10 ]
do
	if [ $i -eq 8 ]; then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	((i++))

done