#!/usr/bin/env bash
#Combines while loops and case statement on 20 iterations of a string.
#displays 4 and then bad luck from China for the 4th loop iteration.
#displays 9 and then bad luck from Japan for the 9th loop iteration.
#displays 17 and then bad luck from Italy for the 17th loop iteration.

i=0

while [ $i -lt 20 ]
do
	case $i in
		3)
		     echo "bad luck from China"
		          ;;
		10)
		     echo "bad luck from Japan"
		          ;;
		16)
		     echo "bad luck from Italy"
	     	     	  ;;
		*)
		     echo "Best School"
	esac
	((i++))

done