#!/usr/bin/env bash
#Prints every minutes needed to count 12 hours.

hr=0

while [ $hr -lt 13 ]
do
	echo "Hour: $hr"

	min=1

	while [ $min -lt 60 ]
	do
		echo "$min"
		((min++))
	done

	((hr++))

done