#!/usr/bin/env bash
#Collect information about a file

if [ -e school ]; then
    echo "school file exists"
    if [ -f school ]; then
        if [ -z "$(cat school)" ]; then
      	    echo "school file is empty"
        elif [ -n "$(cat school)" ]; then
      	    echo "school file is not empty"
        fi
        echo "school is a regular file"
    elif [ -d school ]; then
    	 echo "school file is not empty"
    fi
else
   echo "school file does not exist"
fi

