#!/usr/bin/env bash
#configures an Ubuntu server

facebook="8.8.8.8"

sudo cp /etc/hosts ~/hosts.new

sudo sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new
echo -e "$facebook\tfacebook.com" | sudo tee -a ~/hosts.new

sudo cp -f ~/hosts.new /etc/hosts
