#!/usr/bin/env bash
#Run Nginx as Nginx

chmod 644 /etc/nginx/nginx.conf
sed -Ei 's/\s*#\?*user.*/user nginx;/' /etc/nginx/nginx.conf
sed -Ei 's/(listen(\[::\]:)?80)/listen 8080/' /etc/nginx/sites-enabled/default
pkill apache2

# Restart nginx
service nginx restart